version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    working_dir: /var/www/html
    tty: true
    ports:
      - 8080:80
    links:
      - database
      - redis
    volumes:
      - ./htdocs:/var/www/html

  database:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret

  redis:
    image: redis:latest
